# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('salary', models.IntegerField(max_length=15, verbose_name='Salary')),
                ('spend_now', models.IntegerField(max_length=15, verbose_name='Spend')),
            ],
        ),
        migrations.CreateModel(
            name='Eat',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mysite.People')),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
    ]
